apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: node-exercise
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: node-express
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: node-exercise
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/correlationid: https://github.com/Eknathreddy09/node-express-partnerworkshop-exercise?sub_path=/
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: node-express
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: node-exercise
    spec:
      containers:
      - image: exploreindiatapsolreg.azurecr.io/tap170/tap-packages/build-service/node-exercise-tap-workload@sha256:ed42a299c17852e441d3e4c5d099640de6fc7b97f9caa6b807f5abb62914669d
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

