apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tdp-configurator
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: tdp-configurator
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: tdp-configurator
spec:
  template:
    metadata:
      annotations:
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: tdp-configurator
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: tdp-configurator
    spec:
      containers:
      - image: exploreindiatapsolreg.azurecr.io/tap161/build-service/tdp-configurator-tap-workload@sha256:5011d147327c8134813423998fd560e3669ceccfaf963a429dd9414ca459adf2
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

